version: '3.7'

services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./react-frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


  backend:
    container_name: backend
    build: ./nestjs-backend
    volumes:
      - './nestjs-backend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/db
    command: npm run start
    depends_on:
      - postgres
  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411