version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: dsdatabase
    ports:
      - "5432:5432"
    # networks:
    #   - todo-app

  frontend:
    container_name: frontend
    build: ./react-frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    # depends_on:
    #   - backend
    # networks:
    #   - todo-app


  backend:
    container_name: backend
    build: ./nestjs-backend
    volumes:
      - './nestjs-backend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start
  #   depends_on:
  #     - postgres

# networks:
#   todo-app:
#       name: todo-app
#       driver: bridge